### PR TITLE
Fixes for zppy 3.0.0

### LINKED ISSUE #46: Fixes needed for compatibility with zppy 3.0.0
Zppy just tagged a release candidate 3.0.0rc1.  I did a simple import test with `chemdyg` and this version and I'm seeing:
```
import: 'chemdyg'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/e3sm-unified_1737127818245/test_tmp/run_test.py", line 2, in <module>
    import chemdyg
  File "/home/conda/feedstock_root/build_artifacts/e3sm-unified_1737127818245/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/chemdyg/__init__.py", line 1, in <module>
    from chemdyg.main import chemdyg
  File "/home/conda/feedstock_root/build_artifacts/e3sm-unified_1737127818245/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/chemdyg/main.py", line 5, in <module>
    from zppy.utils import (
ImportError: cannot import name 'checkStatus' from 'zppy.utils' (/home/conda/feedstock_root/build_artifacts/e3sm-unified_1737127818245/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/zppy/utils.py)
```
This is a simple fix -- `checkStatus` has been renamed to `check_status`.

But I assume there will be many more incompatibilities.

A new release candidate for `chemdyg` is needed urgently with these and other fixes to work with the latest zppy so we can test both together in E3SM-Unified.

### PR DESCRIPTION
**Pull request by xylar**
This merge includes some function name changes required for `chemdyg` to work with the latest `zppy` (v3.0.0).

It also update the version number to 1.1.0rc1 so we can make a tag for E3SM-Unified testing.

I have also added a development environment.  `chemdyg` can be tested by running:
```
conda env create -y -n chemdyg_dev -f conda/dev.yml
conda activate chemdyg_dev
python -m pip install -e . --no-deps --no-build-isolation
```

Finally, I made some formatting changes to `main.py` to follow the [PEP8](https://peps.python.org/pep-0008/) formatting standard.  We try to have E3SM python codes follow this standard where possible.

Fixes #46

### CODE REVIEW

**Comment by xylar** [comment]
I went ahead and tagged this as [v1.1.0rc1](https://github.com/E3SM-Project/ChemDyg/releases/tag/v1.1.0rc1) for testing in E3SM-Unified.  We can always make revisions before v1.1.0 actually gets released.

**Review by hsiangheleellnl — APPROVED** [review]

**Review by hsiangheleellnl — APPROVED** [review]

**Review by hsiangheleellnl — APPROVED** [review]

**Review by hsiangheleellnl — APPROVED** [review]

**Comment by hsiangheleellnl** [comment]
@xylar I cannot create chemdyg_dev by the command you suggested

```
(base) [ac.lee1061@chrlogin1 ~]$ conda create -y -n chemdyg_dev -f conda/dev.yml
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - conda/dev.yml

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
Any suggestions?

**Comment by xylar** [comment]
@hsiangheleellnl, the command in this case is `conda env create` rather than `conda create`. It's deeply confusing and makes no sense but that is how it works with yaml files.

**Comment by xylar** [comment]
Thanks for merging the PR!

**Comment by tangq** [comment]
Thank you, @xylar and @hsiangheleellnl , for taking care of this fix. I am recovering from the sick I got at AMS.

@hsiangheleellnl , do you have any other changes to be included in v1.1.0? Perhaps some updates consistent with your paper in review? We should have a non-rc version in the E3SM-Unified release.

**Comment by hsiangheleellnl** [comment]
@xylar I have tried ``` conda env create ``` but it showed different error message

```
(base) [ac.lee1061@chrlogin2 ~]$ conda env create -y -n chemdyg_dev -f conda/dev.yml
usage: conda-env [-h] {create,export,list,remove,update,config} ...
conda-env: error: unrecognized arguments: -y
```
Just tried out without ``` -y ```  and it also does not work. 
```
conda env create -n chemdyg_dev -f conda/dev.yml
Retrieving notices: ...working... done

EnvironmentFileNotFound: '/gpfs/fs1/home/ac.lee1061/conda/dev.yml' file not found
```
Is it my conda issue?

**Comment by hsiangheleellnl** [comment]
@tangq Our previous PRs have been merged to 'main'. Once the test is done, we can release v1.1.0.

**Comment by xylar** [comment]
@hsiangheleellnl, it sounds like you need to check out ~~my branch~~ the `main` branch locally and run from there. But it also sounds like you need to update conda if it doesn't know -y.

**Comment by hsiangheleellnl** [comment]
Hi @xylar, thank you for the help. It works for me to create the new chemdyg_dev environment.  Here are the new problems I have 
```
(chemdyg_dev) [ac.lee1061@chrlogin1 ChemDyg_runscripts]$ zppy -c 20240429.amip.v3atm_on_master.updated.chrysalis.cfg
2025-01-27 16:41:29,376 [INFO]: __main__.py(main:29) >> For help, please see https://e3sm-project.github.io/zppy. Ask questions at https://github.com/E3SM-Project/zppy/discussions/categories/q-a.
2025-01-27 16:41:29,376 [INFO]: __main__.py(main:29) >> For help, please see https://e3sm-project.github.io/zppy. Ask questions at https://github.com/E3SM-Project/zppy/discussions/categories/q-a.
2025-01-27 16:41:29,398 [INFO]: __main__.py(_handle_plugins:105) >> /gpfs/fs1/home/ac.lee1061/ChemDyg_v1.1.0/ChemDyg/chemdyg/defaults/default.ini
2025-01-27 16:41:29,398 [INFO]: __main__.py(_handle_plugins:105) >> /gpfs/fs1/home/ac.lee1061/ChemDyg_v1.1.0/ChemDyg/chemdyg/defaults/default.ini
2025-01-27 16:41:29,401 [INFO]: __main__.py(_validate_config:144) >> Configuration file validation passed.
2025-01-27 16:41:29,401 [INFO]: __main__.py(_validate_config:144) >> Configuration file validation passed.
climo_180x360_aave_1985-1985
...skipping because status file says 'OK'
climo_native_aave_1985-1985
...skipping because status file says 'OK'
ts_atm_hourly_US1.0x1.0_nco_1985-1985-0001
...Submitted batch job 673643
   environment_commands=source /lcrc/soft/climate/e3sm-unified/load_latest_e3sm_unified_chrysalis.sh
ts_atm_hourly_EU1.0x1.0_nco_1985-1985-0001
...Submitted batch job 673644
   environment_commands=source /lcrc/soft/climate/e3sm-unified/load_latest_e3sm_unified_chrysalis.sh
ts_atm_monthly_180x360_aave_1985-1985-0001
...skipping because status file says 'OK'
chemdyg_index_1985-1985
Traceback (most recent call last):
  File "/home/ac.lee1061/zppy_code/zppy/conda/envs/chemdyg_dev/bin/zppy", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/ac.lee1061/zppy_code/zppy/conda/envs/chemdyg_dev/lib/python3.13/site-packages/zppy/__main__.py", line 61, in main
    _launch_scripts(config, script_dir, job_ids_file, plugins)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ac.lee1061/zppy_code/zppy/conda/envs/chemdyg_dev/lib/python3.13/site-packages/zppy/__main__.py", line 255, in _launch_scripts
    existing_bundles = plugin_func(
        plugin["path"], config, script_dir, existing_bundles, job_ids_file
    )
  File "/gpfs/fs1/home/ac.lee1061/ChemDyg_v1.1.0/ChemDyg/chemdyg/main.py", line 131, in chemdyg
    f.write(template.render(**c))
            ~~~~~~~~~~~~~~~^^^^^
  File "/home/ac.lee1061/zppy_code/zppy/conda/envs/chemdyg_dev/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/ac.lee1061/zppy_code/zppy/conda/envs/chemdyg_dev/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/gpfs/fs1/home/ac.lee1061/ChemDyg_v1.1.0/ChemDyg/chemdyg/templates/chemdyg_index.bash", line 2, in top-level template code
    {% include 'slurm_header.sh' %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ac.lee1061/zppy_code/zppy/conda/envs/chemdyg_dev/lib/python3.13/site-packages/jinja2/loaders.py", line 209, in get_source
    raise TemplateNotFound(
    ...<2 lines>...
    )
jinja2.exceptions.TemplateNotFound: 'slurm_header.sh' not found in search paths: '/home/ac.lee1061/zppy_code/zppy/conda/envs/chemdyg_dev/lib/python3.13/site-packages/zppy/templates', '/gpfs/fs1/home/ac.lee1061/ChemDyg_v1.1.0/ChemDyg/chemdyg/templates'
```
Does it mean I miss one file "slurm_header.sh"?

**Comment by xylar** [comment]
@forsyth2, this might be one you can help with.  Has this moved to `zppy-interfaces`?

**Comment by forsyth2** [comment]
@xylar It's not in `zppy-interfaces`, but it _was_ part of that refactor. The paths changed: `zppy/templates/slurm_header.sh` is now `zppy/templates/inclusions/slurm_header.bash`.

**Comment by xylar** [comment]
@hsiangheleellnl, can you make a follow-up PR to fix that path (and then test the same way)?  If it works, please make another PR and I can make another release candidate.
